# Generated by Django 4.2.4 on 2023-08-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_title_alter_post_created_at_alter_post_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='view_count',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='조회수'),
        ),
    ]
