# Generated by Django 4.2.4 on 2023-08-12 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='이름')),
                ('image', models.ImageField(upload_to='', verbose_name='프로필')),
                ('gender', models.TextField(verbose_name='성별')),
                ('age', models.IntegerField(verbose_name='나이')),
                ('school', models.TextField(verbose_name='학력')),
                ('cost', models.IntegerField(verbose_name='수업비용')),
                ('time', models.IntegerField(verbose_name='시간대')),
                ('info', models.TextField(verbose_name='강사정보')),
                ('student', models.TextField(verbose_name='수업 대상')),
                ('feature', models.TextField(verbose_name='특이사항')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_age', models.IntegerField(verbose_name='나이')),
                ('student_phone', models.CharField(max_length=50, verbose_name='전화번호')),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='프로필')),
                ('student_email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('pay', models.TextField(verbose_name='지불방식')),
                ('time', models.IntegerField(verbose_name='시간대')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.class')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
