# Generated by Django 4.2.4 on 2023-08-12 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='class',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='class',
            name='info',
        ),
        migrations.RemoveField(
            model_name='class',
            name='student',
        ),
        migrations.RemoveField(
            model_name='class',
            name='time',
        ),
    ]
