# Generated by Django 4.2.4 on 2023-08-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_class_cost_remove_class_feature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='cost',
            field=models.IntegerField(default=10000, verbose_name='수업비용'),
        ),
        migrations.AddField(
            model_name='class',
            name='feature',
            field=models.TextField(blank=True, null=True, verbose_name='특이사항'),
        ),
        migrations.AddField(
            model_name='class',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='강사정보'),
        ),
        migrations.AddField(
            model_name='class',
            name='student',
            field=models.TextField(blank=True, null=True, verbose_name='수업 대상'),
        ),
        migrations.AddField(
            model_name='class',
            name='time',
            field=models.IntegerField(default=1, verbose_name='시간대'),
        ),
    ]
