# Generated by Django 4.2.4 on 2023-08-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_class_cost_class_feature_class_info_class_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='group',
            field=models.TextField(blank=True, null=True, verbose_name='수업분류'),
        ),
    ]
