# Generated by Django 4.2.4 on 2023-08-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_class_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='time',
        ),
        migrations.AddField(
            model_name='class',
            name='times',
            field=models.TextField(blank=True, null=True, verbose_name='시간대'),
        ),
    ]
