# Generated by Django 4.2.2 on 2023-08-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_class_time_class_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='language',
            field=models.TextField(blank=True, null=True, verbose_name='언어'),
        ),
        migrations.AddField(
            model_name='class',
            name='nationality',
            field=models.TextField(blank=True, null=True, verbose_name='국적'),
        ),
    ]
