# Generated by Django 4.2.4 on 2023-08-14 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0006_class_language_class_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='time',
        ),
        migrations.AddField(
            model_name='class',
            name='account',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='계좌번호'),
        ),
        migrations.AddField(
            model_name='register',
            name='times',
            field=models.TextField(blank=True, null=True, verbose_name='시간대'),
        ),
        migrations.AddField(
            model_name='register',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='register',
            name='student_name',
            field=models.TextField(verbose_name='이름'),
        ),
    ]
