# Generated by Django 4.2.4 on 2023-08-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_register_time_class_account_register_times_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='cost',
            field=models.IntegerField(default=10000, verbose_name='수업비용'),
        ),
    ]
