# Generated by Django 4.2.4 on 2023-08-17 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0009_alter_register_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='스크랩', to=settings.AUTH_USER_MODEL),
        ),
    ]
