# Generated by Django 4.2.4 on 2023-08-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afterschool',
            name='receipt_end',
            field=models.DateField(verbose_name='접수 마감 날짜'),
        ),
        migrations.AlterField(
            model_name='afterschool',
            name='receipt_start',
            field=models.DateField(verbose_name='접수 시작 날짜'),
        ),
        migrations.AlterField(
            model_name='afterschool',
            name='training_end',
            field=models.DateField(verbose_name='교육 마감 날짜'),
        ),
        migrations.AlterField(
            model_name='afterschool',
            name='training_start',
            field=models.DateField(verbose_name='교육 시작 날짜'),
        ),
    ]
