# Generated by Django 4.2.4 on 2023-08-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0002_alter_afterschool_receipt_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionandmulticultural',
            name='support_cycle',
            field=models.CharField(choices=[('일', '일'), ('월', '월'), ('년', '년')], default='일', max_length=20, verbose_name='지원 주기'),
        ),
    ]
