# Generated by Django 4.2.4 on 2023-08-11 04:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0003_alter_regionandmulticultural_support_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='afterschool',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='regionandmulticultural',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
