# Generated by Django 4.2.4 on 2023-08-11 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0005_regionandmulticultural_like_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionandmulticultural',
            name='like_users',
        ),
        migrations.RemoveField(
            model_name='regionandmulticultural',
            name='user',
        ),
    ]
