# Generated by Django 4.2.4 on 2023-08-11 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('informations', '0011_afterschool_like_afterschool_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afterschool',
            name='like',
        ),
        migrations.RemoveField(
            model_name='regionandmulticultural',
            name='like',
        ),
        migrations.AddField(
            model_name='afterschool',
            name='scrap',
            field=models.ManyToManyField(blank=True, null=True, related_name='scrap2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regionandmulticultural',
            name='scrap',
            field=models.ManyToManyField(blank=True, null=True, related_name='scrap1', to=settings.AUTH_USER_MODEL),
        ),
    ]
