# Generated by Django 4.2.4 on 2023-08-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0012_remove_afterschool_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afterschool',
            name='url',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='regionandmulticultural',
            name='url',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='URL'),
        ),
    ]
