# Generated by Django 4.2.4 on 2023-08-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0014_alter_regionandmulticultural_support_cycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionandmulticultural',
            name='tag',
        ),
        migrations.AddField(
            model_name='regionandmulticultural',
            name='tag1',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='태그1'),
        ),
        migrations.AddField(
            model_name='regionandmulticultural',
            name='tag2',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='태그2'),
        ),
    ]
