# Generated by Django 4.2.4 on 2023-08-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0015_remove_regionandmulticultural_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afterschool',
            name='title',
            field=models.CharField(max_length=40, verbose_name='프로그램명'),
        ),
        migrations.AlterField(
            model_name='regionandmulticultural',
            name='content',
            field=models.CharField(max_length=200, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='regionandmulticultural',
            name='title',
            field=models.CharField(max_length=40, verbose_name='제목'),
        ),
    ]
